Vagrant.configure('2') do |config|
  (1..1).each do |i|
  config.vm.define "docker" do |machine|
    machine.vm.box = 'ubuntu/jammy64'
    machine.vm.network "private_network", ip: '192.168.56.39'
	machine.vm.network "public_network"
	machine.ssh.insert_key = false
    machine.vm.hostname = "docker"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "docker_instance-#{i}"
      vb.cpus = '2'
      vb.memory = '3096'
    end
  end
  end
end
